[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
select = ["E","F","I","B","UP"]   # basic errors + imports + bugbear + pyupgrade
ignore = ["E203","E501"]          # match black
